### ISSUE TITLE
isShowWeekView属性无效

### ISSUE THREAD

**Issue by jorkal24** [TangSY/vue3-hash-calendar#1]
isShowWeekView属性设置boolean值无效

**Comment by TangSY** [comment]
亲测有效，看看你是怎么设置的

**Comment by jorkal24** [comment]
![2022-04-29 09 16 52](https://user-images.githubusercontent.com/33830075/165871728-86d999d1-58a1-42ce-9cc0-5911f900ca85.gif)

**Comment by jorkal24** [comment]
使用的是您main分之中examples代码。isShowWeekView设置true无效，设置为可以转换为true的其他类型的值可以生效

**Comment by TangSY** [comment]
已修复
