### ISSUE TITLE
根据日期显示下面dot时 ios不显示

### ISSUE THREAD

**Issue by Silvaer** [TangSY/vue3-hash-calendar#11]
![image](https://user-images.githubusercontent.com/67620369/180954143-61d09d87-fa12-4fc4-99d4-1751141278a2.png)
浏览器正常显示
![fb202d8bbe591c30487403fbd33b011](https://user-images.githubusercontent.com/67620369/180954248-d60f05d1-cbbe-431a-8c4f-7d698837f1e0.jpg)
ios不显示

**Comment by TangSY** [comment]
收到～

**Comment by TangSY** [comment]
已修复
