### ISSUE TITLE
bug一大堆 public不害羞吗

### ISSUE THREAD

**Issue by TangsWang** [TangSY/vue3-hash-calendar#13]

**Comment by TangSY** [comment]
并没有，有问题你能修就自己修，修不了就提，我有空就改改。没人逼你用，零 bug 也不见得你给一分钱，典型的网络乞丐

**Comment by JustGreenHand** [comment]
你吐槽了并随手甩出一个自己写的比这个更好用，我反手就是一个star，现在跟狗叫没什么区别
