### ISSUE TITLE
/examples/main.ts文件缺失了吗

### ISSUE THREAD

**Issue by NotMyYida** [TangSY/vue3-hash-calendar#16]

**Comment by TangSY** [comment]
现在已经不需要这个 examples 文件夹了，该文件夹是 vue2 版本用来存放示例的，vue3 版本的示例可以从文档网站（https://www.hxkj.vip/calendar）的侧边栏，找到对应的属性获取 。
你这个“/examples/main.ts”文件路径是在哪里看到的，可能是迁移文档时遗漏了，我修改一下

**Comment by NotMyYida** [comment]
好的，就在根目录index.html那里

**Comment by TangSY** [comment]
好的
