### ISSUE TITLE
这是一个非常棒的日历组件，能否增加对PC端的支持？

### ISSUE THREAD

**Issue by mqllin** [TangSY/vue3-hash-calendar#17]
css中大量使用的vw,vh等屏幕比例长度单位，导致无法将组件应用在PC端的某一布局区域内。是否能给一个可以复写css的方案以实现在PC端中使用呢？

**Comment by TangSY** [comment]
这个组件就是为移动端设计的，PC端应该去找PC端相应的日历组件较为合适。
如果实在要用的话，可以参考文档里面的这种实现。
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/16008985/207613492-22423679-038a-4511-bcf0-7c3cce27a9fb.png">
