### ISSUE TITLE
在chrome浏览器，滚动时间时出现报错

### ISSUE THREAD

**Issue by starrytky** [TangSY/vue3-hash-calendar#19]
![image](https://user-images.githubusercontent.com/57083144/219283899-99585cb0-c03c-4fcf-a9ea-9a95060e9d3f.png)
![image](https://user-images.githubusercontent.com/57083144/219283994-1eeab9fb-e595-4747-a31d-47b1f31e5fd3.png)

**Comment by TangSY** [comment]
好的，感谢反馈
