### ISSUE TITLE
显示农历时，solar2lunar中月份为何要加一呢？

### ISSUE THREAD

**Issue by eignil** [TangSY/vue3-hash-calendar#38]
如下所示，其中的月份单独加一了。好像是calendar的月份是从0开始的？
PS: 我是用的lunar-typescript的库。
const showLunar = (date) => {
  if (!date || !date.day) return;

  const lunarObj = lunar.solar2lunar(date.year, date.month + 1, date.day);

  return lunarObj.festival || lunarObj.lunarFestival || lunarObj.IDayCn;
};
感谢！

**Comment by eignil** [comment]
好像是calendar的月份是从0开始的？

**Comment by TangSY** [comment]
js中，月份就是从0开始的

**Comment by eignil** [comment]
> js中，月份就是从0开始的

感谢！
