### ISSUE TITLE
组件无法展示，渲染报错

### ISSUE THREAD

**Issue by YangfanY** [TangSY/vue3-hash-calendar#5]
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/31607682/170807164-8a56a9ac-4b79-4d8b-a495-f5d78cb2880a.png">

很奇怪。。

**Comment by YangfanY** [comment]
望回复😩

**Comment by YangfanY** [comment]
<img width="782" alt="d6f541ba84275d8ba66a9a32bf61d4a8" src="https://user-images.githubusercontent.com/31607682/170807757-3dd16ca5-8558-4087-b0ac-8353d9e09621.png">

**Comment by TangSY** [comment]
看看完整代码，最好是给一个可以复现这个问题的在线 demo

**Comment by YangfanY** [comment]
> 看看完整代码，最好是给一个可以复现这个问题的在线 demo

也不是代码的问题，我用yarn安装就报错，使用npm安装就能正常展示。。
